runtime: php55
api_version: 1


handlers:
- url: /api/.*
  script: api.php

- url: (.+).php
  script: \1.php

- url: /memes
  script: memes.php

- url: /browse/.*
  script: pages/restaurants.php

- url: /restaurant/.*
  script: pages/restaurant.php

- url: /login/.*
  script: login.php

- url: /logout/.*
  script: logout.php

- url: /admin/.*
  script: pages/admin.php

- url: /static
  static_dir: static

- url: /.*
  script: index.php
