runtime: php55
api_version: 1


handlers:
- url: /api/.*
  script: api.php

- url: /test
  script: test.php

- url: /memes
  script: memes.php

- url: /pages/.*
  script: index.php

- url: /direct/handle_upload
  script: handle_upload.php

- url: /direct/.*
  script: direct_upload.php

- url: /.*
  script: index.php
