runtime: php55
api_version: 1


handlers:
- url: /api/.*
  script: api.php

- url: (.+).php
  script: \1.php

- url: /test
  script: test.php

- url: /memes
  script: memes.php

- url: /browse/.*
  script: pages/restaurants.php

- url: /restaurant/.*
  script: pages/restaurant.php

- url: /static
  static_dir: static

- url: /direct/.*
  script: direct_upload.php
  
- url: /direct/handle_upload
  script: handle_upload.php


- url: /.*
  script: index.php
