runtime: php55
api_version: 1


handlers:
- url: /api/.*
  script: api.php

- url: /test
  script: test.php

- url: /memes
  script: memes.php

<<<<<<< HEAD
- url: /test
  script: test.php
=======
- url: /.*
  script: index.php
>>>>>>> ca8e064f1cd5a64e2f464c89d30c703d9b46459f
